### ISSUE TITLE
Temperature reading is wrong

### ISSUE THREAD

**Issue by keestux** [adrien3d/IO_LPS22HB#2]
int16_t val = (tempOutH << 8) | (tempOutL & 0xff);
	return 42.5f+val/480.0f;

Where does this formula come from? I think it should just be a division by 100.

	int16_t val = (tempOutH << 8) | (tempOutL & 0xff);
	return val / 100f;

**Comment by keestux** [comment]
It looks like you're mixing up with LPS25.

**Comment by adrien3d** [comment]
Yes, you're right, the formula was from the LPS25h
